versio: 2
jobs:
  build:
    docker:
      - image: djschaper/circleci:1.0-alpine3.7
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
