versio: 2
jobs:
  build:
    docker:
      - image: djschaper/circleci:1.0-alpine3.7
    environment:
      - CIRCLE_BRANCH: integration/circleci
    steps:
      - run:
          name: Set PATH in environment
          command: echo 'export PATH=$CIRCLECI_WORKING_DIR:$PATH' > /etc/profile.d/ash.sh
      - run:
          name: Install Run Dependencies
          command: |
            apk add --no-cache --virtual .run-deps \
            curl \
            drill \
            openssl
      - checkout
      - run:
          name: Test initial script run
          shell: /bin/ash
          command: getsslD
