versio: 2
jobs:
  build:
    docker:
      - image: djschaper/circleci:1.0-alpine3.7
    steps:
      - run:
          name: Install Run Dependencies
          command: |
            apk add --no-cache --virtual .run-deps \
            curl \
            drill \
            openssl
