versio: 2
jobs:
  build:
    docker:
      - image: djschaper/circleci:1.0-alpine3.7
    environment:
      - CIRCLE_BRANCH: integration/circleci
      - PATH: $PATH:$CIRCLE_WORKING_DIRECTORY
    steps:
      - run:
          name: Install Run Dependencies
          command: |
            apk add --no-cache --virtual .run-deps \
            curl \
            drill \
            openssl
      - checkout
      - run:
          name: Test initial script run
          shell: /bin/ash
          command: getsslD
