version: 2
jobs:
  build:
    docker:
      - image: djschaper/circleci:1.1-alpine3.7sc
    environment:
      - CIRCLE_BRANCH: integration/circleci
    shell: /bin/ash
    working_directory: /srv/getsslD
    steps:
      - run:
          name: Install Run Dependencies
          command: |
            apk add --no-cache --virtual .run-deps \
            curl \
            drill \
            openssl
      - checkout
      - run:
          name: Copy getsslD to path'd directory
          command: cp /srv/getsslD/getsslD /bin/
      - run:
          name: Test initial script run
          command: getsslD
      - run:
          name: Shellcheck getsslD
          command: shellcheck /srv/getsslD/getsslD
